version: "3.8"
services:
  battle-service:
    image: strechyna/battle-service:v1
    build: ./battle-service
  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
volumes:
  redis-data: